modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="kaisen"
version="0.0.1"
displayName="Kaisen"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="isotachi"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.kaisen]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration